// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
